export const CURRENCY_SUCCESS = 'CURRENCY_SUCCESS'
export const CURRENCY_REQUEST_HISTORY = 'CURRENCY_REQUEST_HISTORY'
export const CURRENCY_HISTORY_SET_CURRENCY = 'CURRENCY_HISTORY_SET_CURRENCY'
export const CURRENCY_HISTORY_SET_DATE = 'CURRENCY_HISTORY_SET_DATE'

export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT'
export const REMOVE_CONTACT = 'CREATE_NEW_CONTACT'

export const PRELOADER_LAUNCH = 'PRELOADER_LAUNCH'
export const PRELOADER_STOP = 'PRELOADER_STOP'
export const CATCH_ERRORS = 'CATCH_ERRORS'


